CREATE TABLE IF NOT EXISTS orders (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  client_name VARCHAR(120) NOT NULL,
  client_phone VARCHAR(40) NOT NULL,
  client_cpf VARCHAR(20) NOT NULL,
  product VARCHAR(80) NOT NULL,
  format VARCHAR(40) NOT NULL,
  paper VARCHAR(40) NOT NULL,
  quantity INT UNSIGNED NOT NULL,
  payment VARCHAR(40) NOT NULL,
  total DECIMAL(10,2) NOT NULL,
  art_ready VARCHAR(40) NOT NULL,
  client_file VARCHAR(255) DEFAULT NULL,
  client_file_name VARCHAR(255) DEFAULT NULL,
  client_refs TEXT DEFAULT NULL,
  client_refs_names TEXT DEFAULT NULL,
  art_file VARCHAR(255) DEFAULT NULL,
  art_file_name VARCHAR(255) DEFAULT NULL,
  art_uploaded_by VARCHAR(120) DEFAULT NULL,
  art_notes TEXT DEFAULT NULL,
  cancel_requested TINYINT(1) NOT NULL DEFAULT 0,
  cancel_requested_by VARCHAR(120) DEFAULT NULL,
  cancel_requested_at TIMESTAMP NULL DEFAULT NULL,
  status VARCHAR(40) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(120) NOT NULL,
  cpf VARCHAR(20) NOT NULL UNIQUE,
  email VARCHAR(120) DEFAULT NULL,
  phone VARCHAR(40) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
